### ISSUE TITLE
[2.2.1]crush while putting redstone dust on the steam machines

### ISSUE THREAD

**Issue by SarixWired** [TheLimePixel/GregBlock#159]
As the title said,when I'm playing GregBlock which version is 2.2.1, it happens an unexpected error.What I have just been doing is that putting a redstone dust on the top of the steam machines,and then the game crushed. However ,putting redstone dust around the steam machines does not cause game crushed .It's strangle!
    Here is the detail of  crush-report:
java.lang.NullPointerException: Unexpected error
	at gregtech.api.metatileentity.MetaTileEntity.getCoverAtSide(MetaTileEntity.java:346)
	at gregtech.api.metatileentity.MetaTileEntity.canConnectRedstone(MetaTileEntity.java:448)
	at gregtech.api.block.machines.BlockMachine.canConnectRedstone(BlockMachine.java:294)
	at net.minecraft.block.BlockRedstoneWire.canConnectTo(BlockRedstoneWire.java:456)
	at net.minecraft.block.BlockRedstoneWire.func_176340_e(BlockRedstoneWire.java:434)
	at net.minecraft.block.BlockRedstoneWire.func_176341_c(BlockRedstoneWire.java:102)
	at net.minecraft.block.BlockRedstoneWire.func_176221_a(BlockRedstoneWire.java:90)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:423)
	at net.minecraft.block.BlockRedstoneWire.func_185496_a(BlockRedstoneWire.java:54)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:456)
	at net.minecraft.block.Block.func_180636_a(Block.java:631)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:461)
	at net.minecraft.world.World.func_147447_a(World.java:1087)
	at net.minecraft.entity.Entity.func_174822_a(Entity.java:1586)
	at net.minecraft.client.renderer.EntityRenderer.func_78473_a(EntityRenderer.java:357)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1241)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by programgames** [comment]
#160
