### ISSUE TITLE
High Pressure Boiler (probably) bug

### ISSUE THREAD

**Issue by PinkHairedBoi** [TheLimePixel/GregBlock#187]
If i place 3 in a row - it's getting bugged.
I'm playing on server with frien'
Placing 3 in a row - pipes from one side with water, other side for steam

I think this is somehow about boiler trying insert steam in each other or something like that.
2 in a row works fine, once i get 3 in a row i'm getting bug - boilers start to dissapear, lose textures, then lose textures in NEI, then when i dismount with wrench no loot e.t.c.
Bugged.

Tried few times that's not an accident.
![2019-09-10_23 00 26](https://user-images.githubusercontent.com/33196245/64646058-e2c24280-d41e-11e9-8c71-a09d03600900.png)

```
[21:24:27] [Server thread/FATAL] [FML]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  BiggerPacketsPlzCoreMod (biggerpacketsplz-since1.8-1.2.jar)
  RandomPatches (randompatches-1.12.2-1.15.0.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 9/10/19 9:24 PM
Description: Ticking block entity

java.util.NoSuchElementException: key not found: west
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at codechicken.multipart.TileMultipart.getCapability(TileMultipart.scala:593)
        at gregtech.api.metatileentity.MetaTileEntity.pushFluidsIntoNearbyHandlers(MetaTileEntity.java:745)
        at gregtech.common.metatileentities.steam.boiler.SteamBoiler.update(SteamBoiler.java:161)
        at gregtech.api.metatileentity.MetaTileEntityHolder.func_73660_a(MetaTileEntityHolder.java:152)
        at net.minecraft.world.World.func_72939_s(World.java:1835)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at codechicken.multipart.TileMultipart.getCapability(TileMultipart.scala:593)
        at gregtech.api.metatileentity.MetaTileEntity.pushFluidsIntoNearbyHandlers(MetaTileEntity.java:745)
        at gregtech.common.metatileentities.steam.boiler.SteamBoiler.update(SteamBoiler.java:161)
        at gregtech.api.metatileentity.MetaTileEntityHolder.func_73660_a(MetaTileEntityHolder.java:152)

-- Block entity being ticked --
Details:
        Name: gregtech:machine // gregtech.api.metatileentity.MetaTileEntityHolder
        Block type: ID #1817 (tile.unnamed // gregtech.api.block.machines.BlockMachine // gregtech:machine)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-985,77,-13), Chunk: (at 7,4,3 in -62,-1; contains blocks -992,0,-16 to -977,255,-1), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
        Actual block type: ID #1817 (tile.unnamed // gregtech.api.block.machines.BlockMachine // gregtech:machine)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1835)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 1.8.0_221, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 769002792 bytes (733 MB) / 3134717952 bytes (2989 MB) up to 5726797824 bytes (5461 MB)
        JVM Flags: 1 total; -Xmx6G
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP 9.42 Powered by Forge 14.23.5.2808 104 mods loaded, 104 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

        | State  | ID                         | Version                  | Source                                            | Signature                                |
        |:------ |:-------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
        | LCHIJA | minecraft                  | 1.12.2                   | minecraft.jar                                     | None                                     |
        | LCHIJA | mcp                        | 9.42                     | minecraft.jar                                     | None                                     |
        | LCHIJA | FML                        | 8.0.99.99                | forge-1.12.2-14.23.5.2808-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | LCHIJA | forge                      | 14.23.5.2808             | forge-1.12.2-14.23.5.2808-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | LCHIJA | foamfixcore                | 7.7.4                    | minecraft.jar                                     | None                                     |
        | LCHIJA | randompatches              | 1.12.2-1.15.0.2          | randompatches-1.12.2-1.15.0.2.jar                 | None                                     |
        | LCHIJA | appliedenergistics2        | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
        | LCHIJA | mantle                     | 1.12-1.3.3.42            | Mantle-1.12-1.3.3.42.jar                          | None                                     |
        | LCHIJA | chisel                     | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
        | LCHIJA | crafttweaker               | 4.1.16                   | CraftTweaker2-1.12-4.1.16.jar                     | None                                     |
        | LCHIJA | mtlib                      | 3.0.6                    | MTLib-3.0.6.jar                                   | None                                     |
        | LCHIJA | modtweaker                 | 4.0.16                   | modtweaker-4.0.16.jar                             | None                                     |
        | LCHIJA | jei                        | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                         | None                                     |
        | LCHIJA | tinkersextras              | 1.12.2-1.0.9             | TinkersExtras-1.12.2-1.0.9.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
        | LCHIJA | tconstruct                 | 1.12.2-2.12.0.123        | TConstruct-1.12.2-2.12.0.123.jar                  | None                                     |
        | LCHIJA | p455w0rdslib               | 2.0.36                   | p455w0rdslib-1.12.2-2.0.36.jar                    | None                                     |
        | LCHIJA | ae2wtlib                   | 1.0.6                    | AE2WTLib-1.12.2-1.0.6.jar                         | None                                     |
        | LCHIJA | appleskin                  | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
        | LCHIJA | badwithernocookiereloaded  | 1.12.2-3.3.16            | badwithernocookiereloaded-1.12.2-3.3.16.jar       | None                                     |
        | LCHIJA | base                       | 3.12.0                   | base-1.12.2-3.12.0.jar                            | None                                     |
        | LCHIJA | bedpatch                   | 2.2                      | bedpatch-2.2-1.12.2.jar                           | 6bf7527e690fb5e8719b9832bce5000a3e87dfe6 |
        | LCHIJA | betterbuilderswands        | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar | None                                     |
        | LCHIJA | bettermobgriefinggamerule  | 1.12.2-7.0.1             | bettermobgriefinggamerule-1.12.2-7.0.1.jar        | None                                     |
        | LCHIJA | betterquesting             | 3.5.287                  | BetterQuesting-3.5.287.jar                        | None                                     |
        | LCHIJA | biggerpacketsplz           | 1.2                      | biggerpacketsplz-since1.8-1.2.jar                 | 266588b191a3e2974a4a577f282858a3bc07da42 |
        | LCHIJA | forestry                   | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                     | None                                     |
        | LCHIJA | binniecore                 | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
        | LCHIJA | binniedesign               | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
        | LCHIJA | genetics                   | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
        | LCHIJA | botany                     | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
        | LCHIJA | extrabees                  | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
        | LCHIJA | extratrees                 | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
        | LCHIJA | blockcraftery              | 1.12.2-1.2.0             | blockcraftery-1.12.2-1.2.0.jar                    | None                                     |
        | LCHIJA | buildinggadgets            | 2.6.8                    | BuildingGadgets-2.6.8.jar                         | None                                     |
        | LCHIJA | carryon                    | 1.12.1                   | CarryOn MC1.12.2 v1.12.1.jar                      | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
        | LCHIJA | ceramics                   | 1.12-1.3.6               | Ceramics-1.12-1.3.6.jar                           | None                                     |
        | LCHIJA | chameleon                  | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
        | LCHIJA | clumps                     | 3.1.2                    | Clumps-3.1.2.jar                                  | None                                     |
        | LCHIJA | codechickenlib             | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | LCHIJA | consolefilter              | 1.1.1                    | ConsoleFilter-1.12.2-1.1.1.jar                    | None                                     |
        | LCHIJA | containerfix               | 1.0                      | ContainerFix MC1.12.2 v1.0.jar                    | None                                     |
        | LCHIJA | contenttweaker             | 1.12.2-4.9.1             | ContentTweaker-1.12.2-4.9.1.jar                   | None                                     |
        | LCHIJA | craftingtweaks             | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                   | None                                     |
        | LCHIJA | crafttweakerjei            | 2.0.2                    | CraftTweaker2-1.12-4.1.16.jar                     | None                                     |
        | LCHIJA | defaultworldgenerator-port | 1.12-2.3                 | DefaultWorldGenerator-port-1.12-2.3.jar           | None                                     |
        | LCHIJA | forgelin                   | 1.8.2                    | Forgelin-1.8.2.jar                                | None                                     |
        | LCHIJA | exnihilocreatio            | 1.12.2-0.3.9             | exnihilocreatio-1.12.2-0.3.9.jar                  | None                                     |
        | LCHIJA | excompressum               | 3.0.26                   | ExCompressum_1.12.2-3.0.26.jar                    | None                                     |
        | LCHIJA | extracells                 | 2.6.2                    | ExtraCells-1.12.2-2.6.2a.jar                      | None                                     |
        | LCHIJA | fastfurnace                | 1.2.2                    | FastFurnace-1.12.2-1.2.2.jar                      | None                                     |
        | LCHIJA | fastleafdecay              | v14                      | FastLeafDecay-v14.jar                             | None                                     |
        | LCHIJA | fastbench                  | 1.6.1                    | FastWorkbench-1.12.2-1.6.1.jar                    | None                                     |
        | LCHIJA | findme                     | 1.1.0                    | findme-1.12.2-1.1.0-8.jar                         | None                                     |
        | LCHIJA | floodlights                | 1.3.2-14                 | FloodLights-1.12.2-1.3.2-14.jar                   | None                                     |
        | LCHIJA | foamfix                    | 0.10.3-1.12.2            | foamfix-0.10.3-1.12.2.jar                         | None                                     |
        | LCHIJA | forgemultipartcbe          | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | LCHIJA | microblockcbe              | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | None                                     |
        | LCHIJA | minecraftmultipartcbe      | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | None                                     |
        | LCHIJA | forgivingvoid              | 1.0.21                   | ForgivingVoid_1.12.2-1.0.21.jar                   | None                                     |
        | LCHIJA | ftblib                     | 5.4.1.93                 | FTBLib-5.4.1.93.jar                               | None                                     |
        | LCHIJA | ftbutilities               | 5.4.0.88                 | FTBUtilities-5.4.0.88.jar                         | None                                     |
        | LCHIJA | ftbbackups                 | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.2.jar                   | None                                     |
        | LCHIJA | trashcansreborn            | 1.1.0                    | GarbageBins-1.1.1.jar                             | None                                     |
        | LCHIJA | gregtech                   | 1.6.6.374                | gregtech-1.12.2-1.6.6.374.jar                     | None                                     |
        | LCHIJA | gtadditions                | 1.12.2-1.4.2             | GregicAdditions-1.12.2-1.4.2.jar                  | None                                     |
        | LCHIJA | gregblockutils             | 1.12.2-1.2.2             | GregBlockUtilities-1.12.2-1.2.2.jar               | None                                     |
        | LCHIJA | gtconstruct                | 1.12.2-1.0.1             | GregsConstruct-1.12.2-1.0.1.jar                   | None                                     |
        | LCHIJA | gtcebees                   | 1.12.2-1.0.3             | GTCEBees-1.12.2-1.0.3.jar                         | None                                     |
        | LCHIJA | incontrol                  | 3.9.6                    | incontrol-1.12-3.9.6.jar                          | None                                     |
        | LCHIJA | inventorytweaks            | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
        | LCHIJA | itlt                       | 1.0.0                    | itlt-1.12-1.0.0.jar                               | None                                     |
        | LCHIJA | jeibees                    | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                      | None                                     |
        | LCHIJA | kleeslabs                  | 5.4.11                   | KleeSlabs_1.12.2-5.4.11.jar                       | None                                     |
        | LCHIJA | morpheus                   | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                       | None                                     |
        | LCHIJA | mrtjpcore                  | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar           | None                                     |
        | LCHIJA | nmsot                      | 1.2.2-mc1.12.2           | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar           | None                                     |
        | LCHIJA | nuclearcraft               | 2.14c                    | NuclearCraft-2.14c-1.12.2.jar                     | None                                     |
        | LCHIJA | oreexcavation              | 1.4.137                  | OreExcavation-1.4.137.jar                         | None                                     |
        | LCHIJA | packagedauto               | 1.12.2-1.0.1.4           | PackagedAuto-1.12.2-1.0.1.5.jar                   | None                                     |
        | LCHIJA | placebo                    | 1.5.1                    | Placebo-1.12.2-1.5.1.jar                          | None                                     |
        | LCHIJA | pneumaticcraft             | 1.12.2-0.9.3-324         | pneumaticcraft-repressurized-1.12.2-0.9.3-324.jar | None                                     |
        | LCHIJA | projectred-core            | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar               | None                                     |
        | LCHIJA | projectred-integration     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
        | LCHIJA | projectred-transmission    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
        | LCHIJA | projectred-fabrication     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar        | None                                     |
        | LCHIJA | projectred-expansion       | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
        | LCHIJA | projectred-relocation      | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
        | LCHIJA | projectred-transportation  | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
        | LCHIJA | questbook                  | 3.1.1-1.12               | questbook-3.1.1-1.12.jar                          | None                                     |
        | LCHIJA | randomtweaks               | 1.12.2-2.4.3.2           | randomtweaks-1.12.2-2.4.3.2.jar                   | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
        | LCHIJA | simple_trophies            | 1.1.0                    | simpletrophies-1.1.0.jar                          | None                                     |
        | LCHIJA | sourcebottles              | 1.0.1                    | SourceBottles-1.0.2.jar                           | None                                     |
        | LCHIJA | spikemod                   | 1.12-2.1.0               | spikemod-1.12-2.1.0.jar                           | None                                     |
        | LCHIJA | bq_standard                | @VERSION@                | StandardExpansion-3.4.148.jar                     | None                                     |
        | LCHIJA | storagedrawers             | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                   | None                                     |
        | LCHIJA | theoneprobe                | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                       | None                                     |
        | LCHIJA | tinkersjei                 | 1.0                      | tinkersjei-1.0.jar                                | None                                     |
        | LCHIJA | tinkertoolleveling         | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
        | LCHIJA | topaddons                  | 1.12.2-1.10.1            | topaddons-1.12.2-1.10.1.jar                       | None                                     |
        | LCHIJA | ts2k16                     | 1.2.10                   | TS2K16-1.2.10.jar                                 | None                                     |
        | LCHIJA | voidislandcontrol          | 1.5.3                    | voidislandcontrol-1.5.3.jar                       | None                                     |
        | LCHIJA | wct                        | 3.11.88                  | WirelessCraftingTerminal-1.12.2-3.11.88.jar       | None                                     |
        | LCHIJA | justthetips                | 1.12-1.0.1.1             | justthetips-1.12-1.0.1.1.jar                      | None                                     |
        | LCHIJA | mysticallib                | 1.12.2-1.1.1             | mysticallib-1.12.2-1.1.1.jar                      | None                                     |

        Loaded coremods (and transformers):
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
BiggerPacketsPlzCoreMod (biggerpacketsplz-since1.8-1.2.jar)
  net.elnounch.mc.biggerpacketsplz.BiggerPacketsPlzClassTransformer
RandomPatches (randompatches-1.12.2-1.15.0.2.jar)
  com.therandomlabs.randompatches.core.RPTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)

CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
        AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
        Pulsar/tconstruct loaded Pulses:
                - TinkerCommons (Enabled/Forced)
                - TinkerWorld (Enabled/Not Forced)
                - TinkerTools (Enabled/Not Forced)
                - TinkerHarvestTools (Enabled/Forced)
                - TinkerMeleeWeapons (Enabled/Forced)
                - TinkerRangedWeapons (Enabled/Forced)
                - TinkerModifiers (Enabled/Forced)
                - TinkerSmeltery (Enabled/Not Forced)
                - TinkerGadgets (Enabled/Not Forced)
                - TinkerOredict (Enabled/Forced)
                - TinkerIntegration (Enabled/Forced)
                - TinkerFluids (Enabled/Forced)
                - TinkerMaterials (Enabled/Forced)
                - TinkerModelRegister (Enabled/Forced)
                - chiselIntegration (Enabled/Not Forced)
                - craftingtweaksIntegration (Enabled/Not Forced)
                - theoneprobeIntegration (Enabled/Not Forced)

        AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
```

**Comment by PinkHairedBoi** [comment]
Looks like fixed in 2.2.1 but steam sieve ain't working.
